# Generated by Django 3.0.3 on 2020-04-22 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Medykament', 'verbose_name_plural': 'Medykamenty'},
        ),
        migrations.AlterModelOptions(
            name='medicationdetailed',
            options={'verbose_name': 'Dawka Medykamentu', 'verbose_name_plural': 'Dawkowania Medykamentów'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Pacjent', 'verbose_name_plural': 'Pacjenci'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Recepta', 'verbose_name_plural': 'Recepty'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Wizyta', 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.AlterModelOptions(
            name='visittype',
            options={'verbose_name': 'Typ wizyty', 'verbose_name_plural': 'Typy wizyt'},
        ),
        migrations.RemoveField(
            model_name='medicationdetailed',
            name='mediacation',
        ),
        migrations.AddField(
            model_name='medicationdetailed',
            name='medication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dash.Medication', verbose_name='Lek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='medicationdetailed',
            name='dose',
            field=models.CharField(max_length=31, verbose_name='Dawkowanie'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.CharField(max_length=511, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medications',
            field=models.ManyToManyField(to='dash.MedicationDetailed', verbose_name='Leki'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dash.Patient', verbose_name='Pacjent'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.CharField(max_length=1023, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dash.Patient', verbose_name='Pacjent'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='title',
            field=models.CharField(max_length=63, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dash.VisitType', verbose_name='Typ wizyty'),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Nazwa'),
        ),
    ]
